version: "3"
services:

  jenkins:
    user: root
    container_name: jenkins
    image: jenkins:2.60.3-alpine
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - /home/vagrant/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      custom:
        ipv4_address: 172.18.0.2

  nexus:
    user: root
    container_name: nexus
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
      - /home/vagrant/nexus-data:/nexus-data
    networks:
      custom:
        ipv4_address: 172.18.0.3

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.1/16 
